### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by jajaj** [deivisonarthur/Inovarti_FixAddToCartMage18#1]
Hi,
I installed this and now i get this error trying to log in to magento admin

There has been an error processing your request

Mage registry key "_singleton/fixaddtocartmage18/observer" already exists

Trace:
#0 /home/ll/public_html/llka.com/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /home/ll/public_html/llka.com/app/Mage.php(477): Mage::register('_singleton/fixa...', false)
#2 /home/ll/public_html/llka.com/includes/src/__default.php(21427): Mage::getSingleton('fixaddtocartmag...')
#3 /home/ll/public_html/llka.com/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#4 /home/ll/public_html/llka.com/includes/src/__default.php(14078): Mage::dispatchEvent('controller_acti...', Array)
#5 /home/ll/public_html/llka.com/includes/src/Mage_Adminhtml_Controller_Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#6 /home/ll/public_html/llka.com/includes/src/__default.php(13958): Mage_Adminhtml_Controller_Action->preDispatch()
#7 /home/ll/public_html/llka.com/includes/src/__default.php(18331): Mage_Core_Controller_Varien_Action->dispatch('login')
#8 /home/ll/public_html/llka.com/includes/src/__default.php(17865): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/ll/public_html/llka.com/includes/src/__default.php(20465): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/ll/public_html/llka.com/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /home/ll/public_html/llka.com/index.php(87): Mage::run('', 'store')
#12 {main}

**Comment by uncenteredDiv** [comment]
Same Problem here.
I'm using Turpentine 0.6.0 with Magento 1.9.0.1.

Anybody get the fix running?

**Comment by deivisonarthur** [comment]
Yup! introduced the problem with using magento 1.9.1. you can install the fix without problem. he just swapped the formkey and resolved your problem.

Enviado via iPhone

Em 20/08/2014, às 07:01, Skinwalker notifications@github.com escreveu:
